### ISSUE TITLE
NASA now takedown DRL, cannot obtain IPPOP

### ISSUE THREAD

**Issue by dheerapat** [aws-samples/aws-groundstation-s3-data-delivery#1]
NASA now takedown DRL and I cannot use IPPOP are there any alternative software that can be use to tranform L0 data to L1 and L2 ?

**Comment by Viktor-Pankov** [comment]
The Community Satellite Processing Package (CSPP) also supports transformations from L0 to L1 and L2 data. You can check them out here -> https://cimss.ssec.wisc.edu/cspp/
